[
  {
    szm: "A",
    provinceList: [
      {
        shortName: "安徽",
        id: 340000,
        areaList: [
          { id: 340100, shortName: "合肥", areaList: null },
          { id: 340200, shortName: "芜湖", areaList: null },
          { id: 340300, shortName: "蚌埠", areaList: null },
          { id: 340400, shortName: "淮南", areaList: null },
          { id: 340500, shortName: "马鞍山", areaList: null },
          { id: 340600, shortName: "淮北", areaList: null },
          { id: 340700, shortName: "铜陵", areaList: null },
          { id: 340800, shortName: "安庆", areaList: null },
          { id: 341000, shortName: "黄山", areaList: null },
          { id: 341100, shortName: "滁州", areaList: null },
          { id: 341200, shortName: "阜阳", areaList: null },
          { id: 341300, shortName: "宿州", areaList: null },
          { id: 341500, shortName: "六安", areaList: null },
          { id: 341600, shortName: "亳州", areaList: null },
          { id: 341700, shortName: "池州", areaList: null },
          { id: 341800, shortName: "宣城", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "F",
    provinceList: [
      {
        shortName: "福建",
        id: 350000,
        areaList: [
          { id: 350100, shortName: "福州", areaList: null },
          { id: 350200, shortName: "厦门", areaList: null },
          { id: 350300, shortName: "莆田", areaList: null },
          { id: 350400, shortName: "三明", areaList: null },
          { id: 350500, shortName: "泉州", areaList: null },
          { id: 350600, shortName: "漳州", areaList: null },
          { id: 350700, shortName: "南平", areaList: null },
          { id: 350800, shortName: "龙岩", areaList: null },
          { id: 350900, shortName: "宁德", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "G",
    provinceList: [
      {
        shortName: "广东",
        id: 440000,
        areaList: [
          { id: 440100, shortName: "广州", areaList: null },
          { id: 440300, shortName: "深圳", areaList: null },
          { id: 440200, shortName: "韶关", areaList: null },
          { id: 440400, shortName: "珠海", areaList: null },
          { id: 440500, shortName: "汕头", areaList: null },
          { id: 440600, shortName: "佛山", areaList: null },
          { id: 440700, shortName: "江门", areaList: null },
          { id: 440800, shortName: "湛江", areaList: null },
          { id: 440900, shortName: "茂名", areaList: null },
          { id: 441200, shortName: "肇庆", areaList: null },
          { id: 441300, shortName: "惠州", areaList: null },
          { id: 441400, shortName: "梅州", areaList: null },
          { id: 441500, shortName: "汕尾", areaList: null },
          { id: 441600, shortName: "河源", areaList: null },
          { id: 441700, shortName: "阳江", areaList: null },
          { id: 441800, shortName: "清远", areaList: null },
          { id: 441900, shortName: "东莞", areaList: null },
          { id: 442000, shortName: "中山", areaList: null },
          { id: 445100, shortName: "潮州", areaList: null },
          { id: 445200, shortName: "揭阳", areaList: null },
          { id: 445300, shortName: "云浮", areaList: null },
        ],
      },
      {
        shortName: "广西",
        id: 450000,
        areaList: [
          { id: 450100, shortName: "南宁", areaList: null },
          { id: 450200, shortName: "柳州", areaList: null },
          { id: 450300, shortName: "桂林", areaList: null },
          { id: 450400, shortName: "梧州", areaList: null },
          { id: 450500, shortName: "北海", areaList: null },
          { id: 450600, shortName: "防城港", areaList: null },
          { id: 450700, shortName: "钦州", areaList: null },
          { id: 450800, shortName: "贵港", areaList: null },
          { id: 450900, shortName: "玉林", areaList: null },
          { id: 451000, shortName: "百色", areaList: null },
          { id: 451100, shortName: "贺州", areaList: null },
          { id: 451200, shortName: "河池", areaList: null },
          { id: 451300, shortName: "来宾", areaList: null },
          { id: 451400, shortName: "崇左", areaList: null },
        ],
      },
      {
        shortName: "贵州",
        id: 520000,
        areaList: [
          { id: 520100, shortName: "贵阳", areaList: null },
          { id: 520200, shortName: "六盘水", areaList: null },
          { id: 520300, shortName: "遵义", areaList: null },
          { id: 520400, shortName: "安顺", areaList: null },
          { id: 520500, shortName: "毕节", areaList: null },
          { id: 520600, shortName: "铜仁", areaList: null },
          { id: 522300, shortName: "黔西南", areaList: null },
          { id: 522600, shortName: "黔东南", areaList: null },
          { id: 522700, shortName: "黔南", areaList: null },
        ],
      },
      {
        shortName: "甘肃",
        id: 620000,
        areaList: [
          { id: 620100, shortName: "兰州", areaList: null },
          { id: 620200, shortName: "嘉峪关", areaList: null },
          { id: 620300, shortName: "金昌", areaList: null },
          { id: 620400, shortName: "白银", areaList: null },
          { id: 620500, shortName: "天水", areaList: null },
          { id: 620600, shortName: "武威", areaList: null },
          { id: 620700, shortName: "张掖", areaList: null },
          { id: 620800, shortName: "平凉", areaList: null },
          { id: 620900, shortName: "酒泉", areaList: null },
          { id: 621000, shortName: "庆阳", areaList: null },
          { id: 621100, shortName: "定西", areaList: null },
          { id: 621200, shortName: "陇南", areaList: null },
          { id: 622900, shortName: "临夏", areaList: null },
          { id: 623000, shortName: "甘南", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "H",
    provinceList: [
      {
        shortName: "海南",
        id: 460000,
        areaList: [
          { id: 460100, shortName: "海口", areaList: null },
          { id: 460200, shortName: "三亚", areaList: null },
          { id: 460300, shortName: "三沙", areaList: null },
          { id: 469000, shortName: "", areaList: null },
        ],
      },
      {
        shortName: "河南",
        id: 410000,
        areaList: [
          { id: 410100, shortName: "郑州", areaList: null },
          { id: 410200, shortName: "开封", areaList: null },
          { id: 410300, shortName: "洛阳", areaList: null },
          { id: 410400, shortName: "平顶山", areaList: null },
          { id: 410500, shortName: "安阳", areaList: null },
          { id: 410600, shortName: "鹤壁", areaList: null },
          { id: 410700, shortName: "新乡", areaList: null },
          { id: 410800, shortName: "焦作", areaList: null },
          { id: 410900, shortName: "濮阳", areaList: null },
          { id: 411000, shortName: "许昌", areaList: null },
          { id: 411100, shortName: "漯河", areaList: null },
          { id: 411200, shortName: "三门峡", areaList: null },
          { id: 411300, shortName: "南阳", areaList: null },
          { id: 411400, shortName: "商丘", areaList: null },
          { id: 411500, shortName: "信阳", areaList: null },
          { id: 411600, shortName: "周口", areaList: null },
          { id: 411700, shortName: "驻马店", areaList: null },
          { id: 419000, shortName: "", areaList: null },
        ],
      },
      {
        shortName: "黑龙江",
        id: 230000,
        areaList: [
          { id: 230100, shortName: "哈尔滨", areaList: null },
          { id: 230200, shortName: "齐齐哈尔", areaList: null },
          { id: 230300, shortName: "鸡西", areaList: null },
          { id: 230400, shortName: "鹤岗", areaList: null },
          { id: 230500, shortName: "双鸭山", areaList: null },
          { id: 230600, shortName: "大庆", areaList: null },
          { id: 230700, shortName: "伊春", areaList: null },
          { id: 230800, shortName: "佳木斯", areaList: null },
          { id: 230900, shortName: "七台河", areaList: null },
          { id: 231000, shortName: "牡丹江", areaList: null },
          { id: 231100, shortName: "黑河", areaList: null },
          { id: 231200, shortName: "绥化", areaList: null },
          { id: 232700, shortName: "大兴安岭", areaList: null },
        ],
      },
      {
        shortName: "湖北",
        id: 420000,
        areaList: [
          { id: 420100, shortName: "武汉", areaList: null },
          { id: 420200, shortName: "黄石", areaList: null },
          { id: 420300, shortName: "十堰", areaList: null },
          { id: 420500, shortName: "宜昌", areaList: null },
          { id: 420600, shortName: "襄阳", areaList: null },
          { id: 420700, shortName: "鄂州", areaList: null },
          { id: 420800, shortName: "荆门", areaList: null },
          { id: 420900, shortName: "孝感", areaList: null },
          { id: 421000, shortName: "荆州", areaList: null },
          { id: 421100, shortName: "黄冈", areaList: null },
          { id: 421200, shortName: "咸宁", areaList: null },
          { id: 421300, shortName: "随州", areaList: null },
          { id: 422800, shortName: "恩施", areaList: null },
          { id: 429000, shortName: "", areaList: null },
        ],
      },
      {
        shortName: "湖南",
        id: 430000,
        areaList: [
          { id: 430100, shortName: "长沙", areaList: null },
          { id: 430200, shortName: "株洲", areaList: null },
          { id: 430300, shortName: "湘潭", areaList: null },
          { id: 430400, shortName: "衡阳", areaList: null },
          { id: 430500, shortName: "邵阳", areaList: null },
          { id: 430600, shortName: "岳阳", areaList: null },
          { id: 430700, shortName: "常德", areaList: null },
          { id: 430800, shortName: "张家界", areaList: null },
          { id: 430900, shortName: "益阳", areaList: null },
          { id: 431000, shortName: "郴州", areaList: null },
          { id: 431100, shortName: "永州", areaList: null },
          { id: 431200, shortName: "怀化", areaList: null },
          { id: 431300, shortName: "娄底", areaList: null },
          { id: 433100, shortName: "湘西", areaList: null },
        ],
      },
      {
        shortName: "河北",
        id: 130000,
        areaList: [
          { id: 130100, shortName: "石家庄", areaList: null },
          { id: 130200, shortName: "唐山", areaList: null },
          { id: 130300, shortName: "秦皇岛", areaList: null },
          { id: 130400, shortName: "邯郸", areaList: null },
          { id: 130500, shortName: "邢台", areaList: null },
          { id: 130600, shortName: "保定", areaList: null },
          { id: 130700, shortName: "张家口", areaList: null },
          { id: 130800, shortName: "承德", areaList: null },
          { id: 130900, shortName: "沧州", areaList: null },
          { id: 131000, shortName: "廊坊", areaList: null },
          { id: 131100, shortName: "衡水", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "J",
    provinceList: [
      {
        shortName: "江苏",
        id: 320000,
        areaList: [
          { id: 320100, shortName: "南京", areaList: null },
          { id: 320200, shortName: "无锡", areaList: null },
          { id: 320300, shortName: "徐州", areaList: null },
          { id: 320400, shortName: "常州", areaList: null },
          { id: 320500, shortName: "苏州", areaList: null },
          { id: 320600, shortName: "南通", areaList: null },
          { id: 320700, shortName: "连云港", areaList: null },
          { id: 320800, shortName: "淮安", areaList: null },
          { id: 320900, shortName: "盐城", areaList: null },
          { id: 321000, shortName: "扬州", areaList: null },
          { id: 321100, shortName: "镇江", areaList: null },
          { id: 321200, shortName: "泰州", areaList: null },
          { id: 321300, shortName: "宿迁", areaList: null },
        ],
      },
      {
        shortName: "江西",
        id: 360000,
        areaList: [
          { id: 360100, shortName: "南昌", areaList: null },
          { id: 360200, shortName: "景德镇", areaList: null },
          { id: 360300, shortName: "萍乡", areaList: null },
          { id: 360400, shortName: "九江", areaList: null },
          { id: 360500, shortName: "新余", areaList: null },
          { id: 360600, shortName: "鹰潭", areaList: null },
          { id: 360700, shortName: "赣州", areaList: null },
          { id: 360800, shortName: "吉安", areaList: null },
          { id: 360900, shortName: "宜春", areaList: null },
          { id: 361000, shortName: "抚州", areaList: null },
          { id: 361100, shortName: "上饶", areaList: null },
        ],
      },
      {
        shortName: "吉林",
        id: 220000,
        areaList: [
          { id: 220100, shortName: "长春", areaList: null },
          { id: 220200, shortName: "吉林", areaList: null },
          { id: 220300, shortName: "四平", areaList: null },
          { id: 220400, shortName: "辽源", areaList: null },
          { id: 220500, shortName: "通化", areaList: null },
          { id: 220600, shortName: "白山", areaList: null },
          { id: 220700, shortName: "松原", areaList: null },
          { id: 220800, shortName: "白城", areaList: null },
          { id: 222400, shortName: "延边", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "L",
    provinceList: [
      {
        shortName: "辽宁",
        id: 210000,
        areaList: [
          { id: 210100, shortName: "沈阳", areaList: null },
          { id: 210200, shortName: "大连", areaList: null },
          { id: 210300, shortName: "鞍山", areaList: null },
          { id: 210400, shortName: "抚顺", areaList: null },
          { id: 210500, shortName: "本溪", areaList: null },
          { id: 210600, shortName: "丹东", areaList: null },
          { id: 210700, shortName: "锦州", areaList: null },
          { id: 210800, shortName: "营口", areaList: null },
          { id: 210900, shortName: "阜新", areaList: null },
          { id: 211000, shortName: "辽阳", areaList: null },
          { id: 211100, shortName: "盘锦", areaList: null },
          { id: 211200, shortName: "铁岭", areaList: null },
          { id: 211300, shortName: "朝阳", areaList: null },
          { id: 211400, shortName: "葫芦岛", areaList: null },
          { id: 211500, shortName: "金普新区", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "N",
    provinceList: [
      {
        shortName: "宁夏",
        id: 640000,
        areaList: [
          { id: 640100, shortName: "银川", areaList: null },
          { id: 640200, shortName: "石嘴山", areaList: null },
          { id: 640300, shortName: "吴忠", areaList: null },
          { id: 640400, shortName: "固原", areaList: null },
          { id: 640500, shortName: "中卫", areaList: null },
        ],
      },
      {
        shortName: "内蒙古",
        id: 150000,
        areaList: [
          { id: 150100, shortName: "呼和浩特", areaList: null },
          { id: 150200, shortName: "包头", areaList: null },
          { id: 150300, shortName: "乌海", areaList: null },
          { id: 150400, shortName: "赤峰", areaList: null },
          { id: 150500, shortName: "通辽", areaList: null },
          { id: 150600, shortName: "鄂尔多斯", areaList: null },
          { id: 150700, shortName: "呼伦贝尔", areaList: null },
          { id: 150800, shortName: "巴彦淖尔", areaList: null },
          { id: 150900, shortName: "乌兰察布", areaList: null },
          { id: 152200, shortName: "兴安盟", areaList: null },
          { id: 152500, shortName: "锡林郭勒盟", areaList: null },
          { id: 152900, shortName: "阿拉善盟", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "Q",
    provinceList: [
      {
        shortName: "青海",
        id: 630000,
        areaList: [
          { id: 630100, shortName: "西宁", areaList: null },
          { id: 630200, shortName: "海东", areaList: null },
          { id: 632200, shortName: "海北", areaList: null },
          { id: 632300, shortName: "黄南", areaList: null },
          { id: 632500, shortName: "海南", areaList: null },
          { id: 632600, shortName: "果洛", areaList: null },
          { id: 632700, shortName: "玉树", areaList: null },
          { id: 632800, shortName: "海西", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "S",
    provinceList: [
      {
        shortName: "山东",
        id: 370000,
        areaList: [
          { id: 370100, shortName: "济南", areaList: null },
          { id: 370200, shortName: "青岛", areaList: null },
          { id: 370300, shortName: "淄博", areaList: null },
          { id: 370400, shortName: "枣庄", areaList: null },
          { id: 370500, shortName: "东营", areaList: null },
          { id: 370600, shortName: "烟台", areaList: null },
          { id: 370700, shortName: "潍坊", areaList: null },
          { id: 370800, shortName: "济宁", areaList: null },
          { id: 370900, shortName: "泰安", areaList: null },
          { id: 371000, shortName: "威海", areaList: null },
          { id: 371100, shortName: "日照", areaList: null },
          { id: 371200, shortName: "莱芜", areaList: null },
          { id: 371300, shortName: "临沂", areaList: null },
          { id: 371400, shortName: "德州", areaList: null },
          { id: 371500, shortName: "聊城", areaList: null },
          { id: 371600, shortName: "滨州", areaList: null },
          { id: 371700, shortName: "菏泽", areaList: null },
        ],
      },
      {
        shortName: "山西",
        id: 140000,
        areaList: [
          { id: 140100, shortName: "太原", areaList: null },
          { id: 140200, shortName: "大同", areaList: null },
          { id: 140300, shortName: "阳泉", areaList: null },
          { id: 140400, shortName: "长治", areaList: null },
          { id: 140500, shortName: "晋城", areaList: null },
          { id: 140600, shortName: "朔州", areaList: null },
          { id: 140700, shortName: "晋中", areaList: null },
          { id: 140800, shortName: "运城", areaList: null },
          { id: 140900, shortName: "忻州", areaList: null },
          { id: 141000, shortName: "临汾", areaList: null },
          { id: 141100, shortName: "吕梁", areaList: null },
        ],
      },
      {
        shortName: "陕西",
        id: 610000,
        areaList: [
          { id: 610100, shortName: "西安", areaList: null },
          { id: 610200, shortName: "铜川", areaList: null },
          { id: 610300, shortName: "宝鸡", areaList: null },
          { id: 610400, shortName: "咸阳", areaList: null },
          { id: 610500, shortName: "渭南", areaList: null },
          { id: 610600, shortName: "延安", areaList: null },
          { id: 610700, shortName: "汉中", areaList: null },
          { id: 610800, shortName: "榆林", areaList: null },
          { id: 610900, shortName: "安康", areaList: null },
          { id: 611000, shortName: "商洛", areaList: null },
          { id: 611100, shortName: "西咸", areaList: null },
        ],
      },
      {
        shortName: "陕西",
        id: 610000,
        areaList: [
          { id: 610100, shortName: "西安", areaList: null },
          { id: 610200, shortName: "铜川", areaList: null },
          { id: 610300, shortName: "宝鸡", areaList: null },
          { id: 610400, shortName: "咸阳", areaList: null },
          { id: 610500, shortName: "渭南", areaList: null },
          { id: 610600, shortName: "延安", areaList: null },
          { id: 610700, shortName: "汉中", areaList: null },
          { id: 610800, shortName: "榆林", areaList: null },
          { id: 610900, shortName: "安康", areaList: null },
          { id: 611000, shortName: "商洛", areaList: null },
          { id: 611100, shortName: "西咸", areaList: null },
        ],
      },
      {
        shortName: "四川",
        id: 510000,
        areaList: [
          { id: 510100, shortName: "成都", areaList: null },
          { id: 510300, shortName: "自贡", areaList: null },
          { id: 510400, shortName: "攀枝花", areaList: null },
          { id: 510500, shortName: "泸州", areaList: null },
          { id: 510600, shortName: "德阳", areaList: null },
          { id: 510700, shortName: "绵阳", areaList: null },
          { id: 510800, shortName: "广元", areaList: null },
          { id: 510900, shortName: "遂宁", areaList: null },
          { id: 511000, shortName: "内江", areaList: null },
          { id: 511100, shortName: "乐山", areaList: null },
          { id: 511300, shortName: "南充", areaList: null },
          { id: 511400, shortName: "眉山", areaList: null },
          { id: 511500, shortName: "宜宾", areaList: null },
          { id: 511600, shortName: "广安", areaList: null },
          { id: 511700, shortName: "达州", areaList: null },
          { id: 511800, shortName: "雅安", areaList: null },
          { id: 511900, shortName: "巴中", areaList: null },
          { id: 512000, shortName: "资阳", areaList: null },
          { id: 513200, shortName: "阿坝", areaList: null },
          { id: 513300, shortName: "甘孜", areaList: null },
          { id: 513400, shortName: "凉山", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "T",
    provinceList: [
      {
        shortName: "台湾",
        id: 710000,
        areaList: [
          { id: 710100, shortName: "台北", areaList: null },
          { id: 710200, shortName: "高雄", areaList: null },
          { id: 710300, shortName: "基隆", areaList: null },
          { id: 710400, shortName: "台中", areaList: null },
          { id: 710500, shortName: "台南", areaList: null },
          { id: 710600, shortName: "新竹", areaList: null },
          { id: 710700, shortName: "嘉义", areaList: null },
          { id: 710800, shortName: "新北", areaList: null },
          { id: 712200, shortName: "宜兰", areaList: null },
          { id: 712300, shortName: "桃园", areaList: null },
          { id: 712400, shortName: "新竹", areaList: null },
          { id: 712500, shortName: "苗栗", areaList: null },
          { id: 712700, shortName: "彰化", areaList: null },
          { id: 712800, shortName: "南投", areaList: null },
          { id: 712900, shortName: "云林", areaList: null },
          { id: 713000, shortName: "嘉义", areaList: null },
          { id: 713300, shortName: "屏东", areaList: null },
          { id: 713400, shortName: "台东", areaList: null },
          { id: 713500, shortName: "花莲", areaList: null },
          { id: 713600, shortName: "澎湖", areaList: null },
          { id: 713700, shortName: "金门", areaList: null },
          { id: 713800, shortName: "连江", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "X",
    provinceList: [
      {
        shortName: "西藏",
        id: 540000,
        areaList: [
          { id: 540100, shortName: "拉萨", areaList: null },
          { id: 540200, shortName: "日喀则", areaList: null },
          { id: 540300, shortName: "昌都", areaList: null },
          { id: 542200, shortName: "山南", areaList: null },
          { id: 542400, shortName: "那曲", areaList: null },
          { id: 542500, shortName: "阿里", areaList: null },
          { id: 542600, shortName: "林芝", areaList: null },
        ],
      },
      {
        shortName: "新疆",
        id: 650000,
        areaList: [
          { id: 650100, shortName: "乌鲁木齐", areaList: null },
          { id: 650200, shortName: "克拉玛依", areaList: null },
          { id: 652100, shortName: "吐鲁番", areaList: null },
          { id: 652200, shortName: "哈密", areaList: null },
          { id: 652300, shortName: "昌吉", areaList: null },
          { id: 652700, shortName: "博尔塔拉", areaList: null },
          { id: 652800, shortName: "巴音郭楞", areaList: null },
          { id: 652900, shortName: "阿克苏", areaList: null },
          { id: 653000, shortName: "克孜勒苏", areaList: null },
          { id: 653100, shortName: "喀什", areaList: null },
          { id: 653200, shortName: "和田", areaList: null },
          { id: 654000, shortName: "伊犁", areaList: null },
          { id: 654200, shortName: "塔城", areaList: null },
          { id: 654300, shortName: "阿勒泰", areaList: null },
          { id: 659000, shortName: "", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "Y",
    provinceList: [
      {
        shortName: "云南",
        id: 530000,
        areaList: [
          { id: 530100, shortName: "昆明", areaList: null },
          { id: 530300, shortName: "曲靖", areaList: null },
          { id: 530400, shortName: "玉溪", areaList: null },
          { id: 530500, shortName: "保山", areaList: null },
          { id: 530600, shortName: "昭通", areaList: null },
          { id: 530700, shortName: "丽江", areaList: null },
          { id: 530800, shortName: "普洱", areaList: null },
          { id: 530900, shortName: "临沧", areaList: null },
          { id: 532300, shortName: "楚雄", areaList: null },
          { id: 532500, shortName: "红河", areaList: null },
          { id: 532600, shortName: "文山", areaList: null },
          { id: 532800, shortName: "西双版纳", areaList: null },
          { id: 532900, shortName: "大理", areaList: null },
          { id: 533100, shortName: "德宏", areaList: null },
          { id: 533300, shortName: "怒江", areaList: null },
          { id: 533400, shortName: "迪庆", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "Z",
    provinceList: [
      {
        shortName: "浙江",
        id: 330000,
        areaList: [
          { id: 330100, shortName: "杭州", areaList: null },
          { id: 330200, shortName: "宁波", areaList: null },
          { id: 330300, shortName: "温州", areaList: null },
          { id: 330400, shortName: "嘉兴", areaList: null },
          { id: 330500, shortName: "湖州", areaList: null },
          { id: 330600, shortName: "绍兴", areaList: null },
          { id: 330700, shortName: "金华", areaList: null },
          { id: 330800, shortName: "衢州", areaList: null },
          { id: 330900, shortName: "舟山", areaList: null },
          { id: 331000, shortName: "台州", areaList: null },
          { id: 331100, shortName: "丽水", areaList: null },
          { id: 331200, shortName: "舟山新区", areaList: null },
        ],
      },
    ],
  },
  {
    szm: "",
    provinceList: [
      {
        shortName: "其他",
        id: '',
        areaList: [
          { id: 810000, shortName: "香港", areaList: null },
          { id: 820000, shortName: "澳门", areaList: null },

        ],
      },
    ],
  },
];
